{"name": "Existing user try to sign up", "status": "broken", "statusDetails": {"message": "KeyError: 'user with this email already exists.'\n", "trace": "  File \"/Users/santoshdasari/˜/virtualenvs/smoke/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Users/santoshdasari/˜/virtualenvs/smoke/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/then_def.py\", line 100, in then_actor_should_be_able_to_see_error_message\n    should_be_able_to_see_error_message(context, actor_alias, element_name, error_message)\n  File \"/Users/santoshdasari/PycharmProjects/great_magna_tests/tests/smoke/steps/then_impl.py\", line 71, in should_be_able_to_see_error_message\n    if page.should_be_error_message(context.driver, element_name, expected_error_message) == False:\n  File \"/Users/santoshdasari/PycharmProjects/great_magna_tests/tests/smoke/browserpages/greatmagna/login.py\", line 108, in should_be_error_message\n    element_selector = selectors[element_name]\n"}, "steps": [{"name": "Given test authentication is done", "status": "passed", "start": 1616146062746, "stop": 1616146064001}, {"name": "Given \"Robert\" visited \"GreatMagna - Sign Up\" page", "status": "passed", "attachments": [{"name": "visit_page_greatmagna_-_sign_up", "source": "85218906-d3e9-4144-9b30-d610fb6f5390-attachment.jpg", "type": "image/jpg"}], "start": 1616146064001, "stop": 1616146065864}, {"name": "When \"Robert\" decides to enter email address \"santoshtesting10008+755@gmail.com\", password \"Testing@123!\" and click Sign up", "status": "passed", "start": 1616146065864, "stop": 1616146066102}, {"name": "Then \"Robert\" should be on the \"GreatMagna - Sign Up\" Page", "status": "passed", "attachments": [{"name": "should_be_on_greatmagna_-_sign_up", "source": "c37aa161-607f-4be9-a2b1-12dc2679d71d-attachment.jpg", "type": "image/jpg"}], "start": 1616146066102, "stop": 1616146067648}, {"name": "Then \"Robert\" should be able to see error message \"user with this email already exists\" at element \"user with this email already exists.\"", "status": "broken", "statusDetails": {"message": "KeyError: 'user with this email already exists.'\n", "trace": "  File \"/Users/santoshdasari/˜/virtualenvs/smoke/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/Users/santoshdasari/˜/virtualenvs/smoke/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/then_def.py\", line 100, in then_actor_should_be_able_to_see_error_message\n    should_be_able_to_see_error_message(context, actor_alias, element_name, error_message)\n  File \"/Users/santoshdasari/PycharmProjects/great_magna_tests/tests/smoke/steps/then_impl.py\", line 71, in should_be_able_to_see_error_message\n    if page.should_be_error_message(context.driver, element_name, expected_error_message) == False:\n  File \"/Users/santoshdasari/PycharmProjects/great_magna_tests/tests/smoke/browserpages/greatmagna/login.py\", line 108, in should_be_error_message\n    element_selector = selectors[element_name]\n"}, "start": 1616146067648, "stop": 1616146067652}], "start": 1616146060884, "stop": 1616146067725, "uuid": "7a038444-18e3-466b-9272-fae525d93164", "historyId": "607602e710c0454554406c73d376eab4", "labels": [{"name": "severity", "value": "normal"}, {"name": "suite", "value": "Great_Magna_Sign_Up"}, {"name": "tag", "value": "Great-Magna-Sign-Up"}, {"name": "tag", "value": "sign-up-page"}, {"name": "tag", "value": "smoke"}, {"name": "feature", "value": "GreatMagna - Sign up Page"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}], "links": [{"type": "link", "url": "https://uktrade.atlassian.net/browse/XOT-032", "name": "https://uktrade.atlassian.net/browse/XOT-032"}]}